---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: pluralsight-web
  namespace: challenge6
spec:
  gatewayClassName: istio
  listeners:
  - protocol: HTTP
    port: 80
    name: http
    allowedRoutes:
      namespaces:
        from: All